---

- name: Run Docker Container on all servers
  hosts: servers
  become: yes
  tasks:

#    - name: Ensure Docker is installed
#      package:
#        name: docker
#        state: present

    - name: Ensure Nginx is installed
      package:
        name: nginx
        state: present

    - name: Run the webapp container
      docker_container:
        name: webapp_container
        image: webapp_image:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "9091:80"
