---

- name: Run Docker Container on all servers
  hosts: servers
  become: yes
  tasks:

    - name: Run the webapp container
      docker_container:
        name: webapp_container
        image: webapp_image:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "9091:80"
