---

- name: Run Docker Container on all servers
  hosts: all
  become: yes
  tasks:
    
    - name: Ensure Docker is installed
      package:
        name: docker
        state: present

    - name: Run the webapp container
      docker_container:
        name: webapp_container
        image: webapp_image:latest
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "8080:80"
