---

- name: Creating the Docker Image for the webapp
  hosts: servers
  become: yes
  tasks:

  - name: Ensure Python3 is installed
    yum:
      name: python3
      state: present
      update_cache: yes

  - name: Ensure pip3 is installed
    yum:
      name: python3-pip
      state: present

  - name: Ensure Docker SDK for Python is installed
    pip:
      name: docker
      state: present
      executable: pip3

  - name: Start and enable Docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Copy the Docker file  into the servers
    copy:
      src: /home/qjltbarquilla/Group5_FinalProject/webapp/
      dest: /home/qjltbarquilla/Group5_FinalProject/webapp/ 
      owner: qjltbarquilla

  - name: Build Docker image on the servers
    docker_image:
      source: build
      build:
        path: /home/qjltbarquilla/Group5_FinalProject/webapp/
        dockerfile: Dockerfile
        pull: yes
      name: webapp_image
      tag: latest
      state: present
